### ISSUE TITLE
Elections

### ISSUE THREAD

**Issue by Mbites** [TitaniumRogue/ideologies#14]
Hey guys,

The name is Mbites or Marlon, and I was thinking about elections.
So, any ideas? Do we want to keep it as is or do we want to expand on that front?
Maybe streamlined election-events with choosing the winning party or something?

**Comment by TitaniumRogue** [comment]
I would try to expand on it, but I'm a horrible scripter myself, so my help would very minimal.  A good idea though is maybe Millennium Dawn style elections, just plain and simple.

**Comment by Mbites** [comment]
Yeah I also thought about those being a inspiration, I'd feel bad if we copy it though. Maybe tweak the Percentages for the win, even if its only a minor change. Or the possbility of frauds/violent coup elections?

(I'd be able to code these events)

**Comment by TitaniumRogue** [comment]
Yes, that's a pretty good idea. I'm working on adding two more ideologies at the moment, but once I'm done I could help

**Comment by Mbites** [comment]
I am going to work out a system now, probably inspired by the one in Millenium Dawn but I have to adjust it to be more flexible towards that many ideologies. (By the way, I strongly advise against against more Ideologies at least, until we finished the ones we already have.)

**Comment by TitaniumRogue** [comment]
This is great! Sadly though I can't work on anything today as I'm busy, but tomorrow I'll be back. If you could get this done, it would make things a whole lot easier going forward (and no, there are not going to be any more ideologies)

**Comment by sobonu** [comment]
Could we also add Civil war events?

**Comment by Mbites** [comment]
I think those are planned yes, but they dont really require any coding skills, just copy the vanilla ones and adjust them for the new ideologies. Of course Localisation has to be changed as well.

**Comment by TitaniumRogue** [comment]
I'm just asking, but what is your progress on the election events?

**Comment by Mbites** [comment]
Nah, I encountered a few problems but nothing that will really hinder progress, I am just really busy with other things too so my time to work on the project is limited. Sorry.
