### ISSUE TITLE
POR_absolute_monarchy

### ISSUE THREAD

**Issue by bowserking123** [TitaniumRogue/ideologies#16]
![por_absolute_monarchy](https://user-images.githubusercontent.com/7192135/29497617-10c5bcd6-85b9-11e7-92d4-139edfa522d4.png)

**Comment by Mbites** [comment]
Probably also applies to Imperialist? (Even though the imperialist ideology is quite odd)

**Comment by TitaniumRogue** [comment]
Yes, that would also apply to imperialism (the new name is feudalism)
