### ISSUE TITLE
Party Leaders ?

### ISSUE THREAD

**Issue by ghost** [TitaniumRogue/ideologies#47]
Sup Guys !
I have already research a big part of the German party leaders so i was interested if  someone can give me a little tutorial how to add party leaders , add portraits for them etc.
Thanks!

**Comment by Mbites** [comment]
In the country history files is a command called "create_country_leader" or something along those lines use them for reference, they are not too difficult to understand.

**Comment by ghost** [comment]
Okay i get how to make them , but in which folder should i put the portaits ?

**Comment by TitaniumRogue** [comment]
There should be a folder called 'leaders' or something to that degree in the gfx folder
