### ISSUE TITLE
Danish Party names

### ISSUE THREAD

**Issue by sobonu** [TitaniumRogue/ideologies#54]
I just want know what was wrong with my Danish Party Localization, so i can fix it.
#45

**Comment by TitaniumRogue** [comment]
Nothing was wrong with it, I just merged it into my local files, and forgot to upload it

**Comment by sobonu** [comment]
It said you closed the pull request instead of merging it so kinda thought you rejected it or something. I'm new to using github so that's probably why i'm confused by this.
