### ISSUE TITLE
You wrote "Leninism" wrong...

### ISSUE THREAD

**Issue by sobonu** [TitaniumRogue/ideologies#74]
![not good](https://user-images.githubusercontent.com/31180501/29999064-fa11824a-903a-11e7-8e47-b58b82d11421.PNG)
Does this mean we have to go through the localizations to fix this? or can we just leave it alone.

**Comment by TitaniumRogue** [comment]
Don't worry, I'll fix it ;)

**Comment by sobonu** [comment]
Okay good.
